// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Migrations;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksEntities))]
    [Migration("20260419081150_SeedRegionData")]
    partial class SeedRegionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Domain_Model.Difficulty", b =>
                {
                    b.Property<Guid>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DifficultyId");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            DifficultyId = new Guid("7a2de582-caf2-46fa-a3c2-ff395c2078a7"),
                            Name = "Easy"
                        },
                        new
                        {
                            DifficultyId = new Guid("e4cb354e-15b2-4061-b7b0-7581f0c74926"),
                            Name = "Medium"
                        },
                        new
                        {
                            DifficultyId = new Guid("6372c198-ccb1-47f5-b420-9111a98c5cf8"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Domain_Model.Region", b =>
                {
                    b.Property<Guid>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            RegionId = new Guid("920b4881-b3b6-4422-aa07-8e00b0069b0e"),
                            Code = "Region1",
                            Name = "Region North"
                        },
                        new
                        {
                            RegionId = new Guid("f5af8551-16cc-4e1e-bef5-12a4d7afec77"),
                            Code = "Region2",
                            Name = "Region South"
                        },
                        new
                        {
                            RegionId = new Guid("15a85ab3-0153-4021-8cea-2ef6ffd56598"),
                            Code = "Region3",
                            Name = "Region East"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Domain_Model.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Domain_Model.Walks", b =>
                {
                    b.HasOne("NZWalks.API.Domain_Model.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Domain_Model.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
